apiVersion: v1
kind: Pod
metadata:
  name: operator
  namespace: go-k8s-operator
spec:
  containers:
    - name: operator
      image: liburdi/go-k8s-operator:0.1.1
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"
      command: [ "./go-k8s-operator" ]
      args: [ "--image", "liburdi/go-k8s-job-example:0.1.1", "--name", "job-example-11" ]