kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: go-k8s-operator
  name: go-k8s-operator-role
rules:
  - apiGroups: [ "batch" ]
    resources: [ "jobs", "pods", "cronjobs" ]
    verbs: [ "*" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: go-k8s-operator-role-rolebinding
  namespace: go-k8s-operator
subjects:
  - kind: ServiceAccount
    name: go-k8s-operator
    namespace: go-k8s-operator
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io

